/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/messagetemplatecontent": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.messagetemplatecontent.id"];
          inserted_at?: parameters["rowFilter.messagetemplatecontent.inserted_at"];
          updated_at?: parameters["rowFilter.messagetemplatecontent.updated_at"];
          istype?: parameters["rowFilter.messagetemplatecontent.istype"];
          istext?: parameters["rowFilter.messagetemplatecontent.istext"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["messagetemplatecontent"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** messagetemplatecontent */
          messagetemplatecontent?: definitions["messagetemplatecontent"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.messagetemplatecontent.id"];
          inserted_at?: parameters["rowFilter.messagetemplatecontent.inserted_at"];
          updated_at?: parameters["rowFilter.messagetemplatecontent.updated_at"];
          istype?: parameters["rowFilter.messagetemplatecontent.istype"];
          istext?: parameters["rowFilter.messagetemplatecontent.istext"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.messagetemplatecontent.id"];
          inserted_at?: parameters["rowFilter.messagetemplatecontent.inserted_at"];
          updated_at?: parameters["rowFilter.messagetemplatecontent.updated_at"];
          istype?: parameters["rowFilter.messagetemplatecontent.istype"];
          istext?: parameters["rowFilter.messagetemplatecontent.istext"];
        };
        body: {
          /** messagetemplatecontent */
          messagetemplatecontent?: definitions["messagetemplatecontent"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/talks": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.talks.id"];
          inserted_at?: parameters["rowFilter.talks.inserted_at"];
          updated_at?: parameters["rowFilter.talks.updated_at"];
          istype?: parameters["rowFilter.talks.istype"];
          messagetype?: parameters["rowFilter.talks.messagetype"];
          messageid?: parameters["rowFilter.talks.messageid"];
          messagetext?: parameters["rowFilter.talks.messagetext"];
          webhookeventid?: parameters["rowFilter.talks.webhookeventid"];
          isredelivery?: parameters["rowFilter.talks.isredelivery"];
          istimestamp?: parameters["rowFilter.talks.istimestamp"];
          replytoken?: parameters["rowFilter.talks.replytoken"];
          ismode?: parameters["rowFilter.talks.ismode"];
          /** このメッセージに対して、返信したかどうか */
          isReply?: parameters["rowFilter.talks.isReply"];
          userId?: parameters["rowFilter.talks.userId"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["talks"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** talks */
          talks?: definitions["talks"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.talks.id"];
          inserted_at?: parameters["rowFilter.talks.inserted_at"];
          updated_at?: parameters["rowFilter.talks.updated_at"];
          istype?: parameters["rowFilter.talks.istype"];
          messagetype?: parameters["rowFilter.talks.messagetype"];
          messageid?: parameters["rowFilter.talks.messageid"];
          messagetext?: parameters["rowFilter.talks.messagetext"];
          webhookeventid?: parameters["rowFilter.talks.webhookeventid"];
          isredelivery?: parameters["rowFilter.talks.isredelivery"];
          istimestamp?: parameters["rowFilter.talks.istimestamp"];
          replytoken?: parameters["rowFilter.talks.replytoken"];
          ismode?: parameters["rowFilter.talks.ismode"];
          /** このメッセージに対して、返信したかどうか */
          isReply?: parameters["rowFilter.talks.isReply"];
          userId?: parameters["rowFilter.talks.userId"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.talks.id"];
          inserted_at?: parameters["rowFilter.talks.inserted_at"];
          updated_at?: parameters["rowFilter.talks.updated_at"];
          istype?: parameters["rowFilter.talks.istype"];
          messagetype?: parameters["rowFilter.talks.messagetype"];
          messageid?: parameters["rowFilter.talks.messageid"];
          messagetext?: parameters["rowFilter.talks.messagetext"];
          webhookeventid?: parameters["rowFilter.talks.webhookeventid"];
          isredelivery?: parameters["rowFilter.talks.isredelivery"];
          istimestamp?: parameters["rowFilter.talks.istimestamp"];
          replytoken?: parameters["rowFilter.talks.replytoken"];
          ismode?: parameters["rowFilter.talks.ismode"];
          /** このメッセージに対して、返信したかどうか */
          isReply?: parameters["rowFilter.talks.isReply"];
          userId?: parameters["rowFilter.talks.userId"];
        };
        body: {
          /** talks */
          talks?: definitions["talks"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/reserve": {
    get: {
      parameters: {
        query: {
          created_at?: parameters["rowFilter.reserve.created_at"];
          date?: parameters["rowFilter.reserve.date"];
          member?: parameters["rowFilter.reserve.member"];
          status?: parameters["rowFilter.reserve.status"];
          lineid?: parameters["rowFilter.reserve.lineid"];
          reserveid?: parameters["rowFilter.reserve.reserveid"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["reserve"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** reserve */
          reserve?: definitions["reserve"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          created_at?: parameters["rowFilter.reserve.created_at"];
          date?: parameters["rowFilter.reserve.date"];
          member?: parameters["rowFilter.reserve.member"];
          status?: parameters["rowFilter.reserve.status"];
          lineid?: parameters["rowFilter.reserve.lineid"];
          reserveid?: parameters["rowFilter.reserve.reserveid"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          created_at?: parameters["rowFilter.reserve.created_at"];
          date?: parameters["rowFilter.reserve.date"];
          member?: parameters["rowFilter.reserve.member"];
          status?: parameters["rowFilter.reserve.status"];
          lineid?: parameters["rowFilter.reserve.lineid"];
          reserveid?: parameters["rowFilter.reserve.reserveid"];
        };
        body: {
          /** reserve */
          reserve?: definitions["reserve"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/messagetemplate": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.messagetemplate.id"];
          inserted_at?: parameters["rowFilter.messagetemplate.inserted_at"];
          updated_at?: parameters["rowFilter.messagetemplate.updated_at"];
          content?: parameters["rowFilter.messagetemplate.content"];
          name?: parameters["rowFilter.messagetemplate.name"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["messagetemplate"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** messagetemplate */
          messagetemplate?: definitions["messagetemplate"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.messagetemplate.id"];
          inserted_at?: parameters["rowFilter.messagetemplate.inserted_at"];
          updated_at?: parameters["rowFilter.messagetemplate.updated_at"];
          content?: parameters["rowFilter.messagetemplate.content"];
          name?: parameters["rowFilter.messagetemplate.name"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.messagetemplate.id"];
          inserted_at?: parameters["rowFilter.messagetemplate.inserted_at"];
          updated_at?: parameters["rowFilter.messagetemplate.updated_at"];
          content?: parameters["rowFilter.messagetemplate.content"];
          name?: parameters["rowFilter.messagetemplate.name"];
        };
        body: {
          /** messagetemplate */
          messagetemplate?: definitions["messagetemplate"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/urls_tags": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.urls_tags.id"];
          created_at?: parameters["rowFilter.urls_tags.created_at"];
          url_id?: parameters["rowFilter.urls_tags.url_id"];
          tag_id?: parameters["rowFilter.urls_tags.tag_id"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["urls_tags"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** urls_tags */
          urls_tags?: definitions["urls_tags"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.urls_tags.id"];
          created_at?: parameters["rowFilter.urls_tags.created_at"];
          url_id?: parameters["rowFilter.urls_tags.url_id"];
          tag_id?: parameters["rowFilter.urls_tags.tag_id"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.urls_tags.id"];
          created_at?: parameters["rowFilter.urls_tags.created_at"];
          url_id?: parameters["rowFilter.urls_tags.url_id"];
          tag_id?: parameters["rowFilter.urls_tags.tag_id"];
        };
        body: {
          /** urls_tags */
          urls_tags?: definitions["urls_tags"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/autoreplymessage": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.autoreplymessage.id"];
          inserted_at?: parameters["rowFilter.autoreplymessage.inserted_at"];
          updated_at?: parameters["rowFilter.autoreplymessage.updated_at"];
          trigger?: parameters["rowFilter.autoreplymessage.trigger"];
          content?: parameters["rowFilter.autoreplymessage.content"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["autoreplymessage"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** autoreplymessage */
          autoreplymessage?: definitions["autoreplymessage"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.autoreplymessage.id"];
          inserted_at?: parameters["rowFilter.autoreplymessage.inserted_at"];
          updated_at?: parameters["rowFilter.autoreplymessage.updated_at"];
          trigger?: parameters["rowFilter.autoreplymessage.trigger"];
          content?: parameters["rowFilter.autoreplymessage.content"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.autoreplymessage.id"];
          inserted_at?: parameters["rowFilter.autoreplymessage.inserted_at"];
          updated_at?: parameters["rowFilter.autoreplymessage.updated_at"];
          trigger?: parameters["rowFilter.autoreplymessage.trigger"];
          content?: parameters["rowFilter.autoreplymessage.content"];
        };
        body: {
          /** autoreplymessage */
          autoreplymessage?: definitions["autoreplymessage"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/countup": {
    get: {
      parameters: {
        query: {
          url?: parameters["rowFilter.countup.url"];
          count?: parameters["rowFilter.countup.count"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["countup"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** countup */
          countup?: definitions["countup"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          url?: parameters["rowFilter.countup.url"];
          count?: parameters["rowFilter.countup.count"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          url?: parameters["rowFilter.countup.url"];
          count?: parameters["rowFilter.countup.count"];
        };
        body: {
          /** countup */
          countup?: definitions["countup"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/pushmessages": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.pushmessages.id"];
          inserted_at?: parameters["rowFilter.pushmessages.inserted_at"];
          updated_at?: parameters["rowFilter.pushmessages.updated_at"];
          message?: parameters["rowFilter.pushmessages.message"];
          touserid?: parameters["rowFilter.pushmessages.touserid"];
          istype?: parameters["rowFilter.pushmessages.istype"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["pushmessages"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** pushmessages */
          pushmessages?: definitions["pushmessages"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.pushmessages.id"];
          inserted_at?: parameters["rowFilter.pushmessages.inserted_at"];
          updated_at?: parameters["rowFilter.pushmessages.updated_at"];
          message?: parameters["rowFilter.pushmessages.message"];
          touserid?: parameters["rowFilter.pushmessages.touserid"];
          istype?: parameters["rowFilter.pushmessages.istype"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.pushmessages.id"];
          inserted_at?: parameters["rowFilter.pushmessages.inserted_at"];
          updated_at?: parameters["rowFilter.pushmessages.updated_at"];
          message?: parameters["rowFilter.pushmessages.message"];
          touserid?: parameters["rowFilter.pushmessages.touserid"];
          istype?: parameters["rowFilter.pushmessages.istype"];
        };
        body: {
          /** pushmessages */
          pushmessages?: definitions["pushmessages"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/tags": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.tags.id"];
          inserted_at?: parameters["rowFilter.tags.inserted_at"];
          updated_at?: parameters["rowFilter.tags.updated_at"];
          name?: parameters["rowFilter.tags.name"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["tags"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** tags */
          tags?: definitions["tags"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.tags.id"];
          inserted_at?: parameters["rowFilter.tags.inserted_at"];
          updated_at?: parameters["rowFilter.tags.updated_at"];
          name?: parameters["rowFilter.tags.name"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.tags.id"];
          inserted_at?: parameters["rowFilter.tags.inserted_at"];
          updated_at?: parameters["rowFilter.tags.updated_at"];
          name?: parameters["rowFilter.tags.name"];
        };
        body: {
          /** tags */
          tags?: definitions["tags"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/customers": {
    get: {
      parameters: {
        query: {
          lineid?: parameters["rowFilter.customers.lineid"];
          phone?: parameters["rowFilter.customers.phone"];
          email?: parameters["rowFilter.customers.email"];
          address?: parameters["rowFilter.customers.address"];
          inserted_at?: parameters["rowFilter.customers.inserted_at"];
          updated_at?: parameters["rowFilter.customers.updated_at"];
          username?: parameters["rowFilter.customers.username"];
          displayname?: parameters["rowFilter.customers.displayname"];
          pictureurl?: parameters["rowFilter.customers.pictureurl"];
          status?: parameters["rowFilter.customers.status"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["customers"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** customers */
          customers?: definitions["customers"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          lineid?: parameters["rowFilter.customers.lineid"];
          phone?: parameters["rowFilter.customers.phone"];
          email?: parameters["rowFilter.customers.email"];
          address?: parameters["rowFilter.customers.address"];
          inserted_at?: parameters["rowFilter.customers.inserted_at"];
          updated_at?: parameters["rowFilter.customers.updated_at"];
          username?: parameters["rowFilter.customers.username"];
          displayname?: parameters["rowFilter.customers.displayname"];
          pictureurl?: parameters["rowFilter.customers.pictureurl"];
          status?: parameters["rowFilter.customers.status"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          lineid?: parameters["rowFilter.customers.lineid"];
          phone?: parameters["rowFilter.customers.phone"];
          email?: parameters["rowFilter.customers.email"];
          address?: parameters["rowFilter.customers.address"];
          inserted_at?: parameters["rowFilter.customers.inserted_at"];
          updated_at?: parameters["rowFilter.customers.updated_at"];
          username?: parameters["rowFilter.customers.username"];
          displayname?: parameters["rowFilter.customers.displayname"];
          pictureurl?: parameters["rowFilter.customers.pictureurl"];
          status?: parameters["rowFilter.customers.status"];
        };
        body: {
          /** customers */
          customers?: definitions["customers"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/urls": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.urls.id"];
          name?: parameters["rowFilter.urls.name"];
          createdAt?: parameters["rowFilter.urls.createdAt"];
          updatedAt?: parameters["rowFilter.urls.updatedAt"];
          click?: parameters["rowFilter.urls.click"];
          impression?: parameters["rowFilter.urls.impression"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["urls"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** urls */
          urls?: definitions["urls"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.urls.id"];
          name?: parameters["rowFilter.urls.name"];
          createdAt?: parameters["rowFilter.urls.createdAt"];
          updatedAt?: parameters["rowFilter.urls.updatedAt"];
          click?: parameters["rowFilter.urls.click"];
          impression?: parameters["rowFilter.urls.impression"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.urls.id"];
          name?: parameters["rowFilter.urls.name"];
          createdAt?: parameters["rowFilter.urls.createdAt"];
          updatedAt?: parameters["rowFilter.urls.updatedAt"];
          click?: parameters["rowFilter.urls.click"];
          impression?: parameters["rowFilter.urls.impression"];
        };
        body: {
          /** urls */
          urls?: definitions["urls"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/customers_tags": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.customers_tags.id"];
          created_at?: parameters["rowFilter.customers_tags.created_at"];
          tag_id?: parameters["rowFilter.customers_tags.tag_id"];
          customer_id?: parameters["rowFilter.customers_tags.customer_id"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["customers_tags"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** customers_tags */
          customers_tags?: definitions["customers_tags"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.customers_tags.id"];
          created_at?: parameters["rowFilter.customers_tags.created_at"];
          tag_id?: parameters["rowFilter.customers_tags.tag_id"];
          customer_id?: parameters["rowFilter.customers_tags.customer_id"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.customers_tags.id"];
          created_at?: parameters["rowFilter.customers_tags.created_at"];
          tag_id?: parameters["rowFilter.customers_tags.tag_id"];
          customer_id?: parameters["rowFilter.customers_tags.customer_id"];
        };
        body: {
          /** customers_tags */
          customers_tags?: definitions["customers_tags"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  messagetemplatecontent: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     * @default extensions.uuid_generate_v4()
     */
    id: string;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    inserted_at: string;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    updated_at: string;
    /** Format: character varying */
    istype: string;
    /** Format: character varying */
    istext: string;
  };
  talks: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     * @default extensions.uuid_generate_v4()
     */
    id: string;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    inserted_at: string;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    updated_at: string;
    /** Format: character varying */
    istype?: string;
    /** Format: character varying */
    messagetype?: string;
    /** Format: character varying */
    messageid?: string;
    /** Format: character varying */
    messagetext?: string;
    /** Format: character varying */
    webhookeventid?: string;
    /** Format: boolean */
    isredelivery?: boolean;
    /** Format: character varying */
    istimestamp?: string;
    /** Format: character varying */
    replytoken?: string;
    /** Format: character varying */
    ismode?: string;
    /**
     * Format: boolean
     * @description このメッセージに対して、返信したかどうか
     * @default false
     */
    isReply: boolean;
    /**
     * Format: character varying
     * @description Note:
     * This is a Foreign Key to `customers.lineid`.<fk table='customers' column='lineid'/>
     */
    userId: string;
  };
  reserve: {
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /** Format: date */
    date: string;
    /** Format: integer */
    member: number;
    /** Format: text */
    status: string;
    /**
     * Format: character varying
     * @description Note:
     * This is a Foreign Key to `customers.lineid`.<fk table='customers' column='lineid'/>
     */
    lineid: string;
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     * @default extensions.uuid_generate_v4()
     */
    reserveid: string;
  };
  messagetemplate: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     * @default extensions.uuid_generate_v4()
     */
    id: string;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    inserted_at: string;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    updated_at: string;
    /** Format: ARRAY */
    content: unknown[];
    /** Format: character varying */
    name: string;
  };
  urls_tags: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     * @default extensions.uuid_generate_v4()
     */
    id: string;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /**
     * Format: uuid
     * @description Note:
     * This is a Foreign Key to `urls.id`.<fk table='urls' column='id'/>
     */
    url_id: string;
    /**
     * Format: uuid
     * @description Note:
     * This is a Foreign Key to `tags.id`.<fk table='tags' column='id'/>
     */
    tag_id: string;
  };
  autoreplymessage: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     * @default extensions.uuid_generate_v4()
     */
    id: string;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    inserted_at: string;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    updated_at: string;
    /** Format: character varying */
    trigger: string;
    /** Format: ARRAY */
    content: unknown[];
  };
  countup: {
    /**
     * Format: text
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    url: string;
    /** Format: integer */
    count?: number;
  };
  pushmessages: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     * @default extensions.uuid_generate_v4()
     */
    id: string;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    inserted_at: string;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    updated_at: string;
    /** Format: character varying */
    message?: string;
    /**
     * Format: character varying
     * @description Note:
     * This is a Foreign Key to `customers.lineid`.<fk table='customers' column='lineid'/>
     */
    touserid: string;
    /**
     * Format: character varying
     * @default pushmessage
     */
    istype: string;
  };
  tags: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     * @default extensions.uuid_generate_v4()
     */
    id: string;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    inserted_at: string;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    updated_at: string;
    /** Format: character varying */
    name: string;
  };
  customers: {
    /**
     * Format: character varying
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    lineid: string;
    /** Format: character varying */
    phone?: string;
    /** Format: character varying */
    email?: string;
    /** Format: character varying */
    address?: string;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    inserted_at?: string;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    updated_at?: string;
    /** Format: character varying */
    username?: string;
    /** Format: character varying */
    displayname?: string;
    /** Format: text */
    pictureurl?: string;
    /**
     * Format: character varying
     * @default follow
     */
    status?: string;
  };
  urls: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     * @default extensions.uuid_generate_v4()
     */
    id: string;
    /** Format: character varying */
    name: string;
    /**
     * Format: timestamp with time zone
     * @default (now() AT TIME ZONE 'utc'::text)
     */
    createdAt: string;
    /**
     * Format: timestamp with time zone
     * @default (now() AT TIME ZONE 'utc'::text)
     */
    updatedAt: string;
    /**
     * Format: integer
     * @default 0
     */
    click?: number;
    /**
     * Format: integer
     * @default 0
     */
    impression?: number;
  };
  customers_tags: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     * @default extensions.uuid_generate_v4()
     */
    id: string;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /**
     * Format: uuid
     * @description Note:
     * This is a Foreign Key to `tags.id`.<fk table='tags' column='id'/>
     */
    tag_id: string;
    /**
     * Format: character varying
     * @description Note:
     * This is a Foreign Key to `customers.lineid`.<fk table='customers' column='lineid'/>
     */
    customer_id: string;
  };
}

export interface parameters {
  /**
   * @description Preference
   * @enum {string}
   */
  preferParams: "params=single-object";
  /**
   * @description Preference
   * @enum {string}
   */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /**
   * @description Preference
   * @enum {string}
   */
  preferCount: "count=none";
  /** @description Filtering Columns */
  select: string;
  /** @description On Conflict */
  on_conflict: string;
  /** @description Ordering */
  order: string;
  /** @description Limiting and Pagination */
  range: string;
  /**
   * @description Limiting and Pagination
   * @default items
   */
  rangeUnit: string;
  /** @description Limiting and Pagination */
  offset: string;
  /** @description Limiting and Pagination */
  limit: string;
  /** @description messagetemplatecontent */
  "body.messagetemplatecontent": definitions["messagetemplatecontent"];
  /** Format: uuid */
  "rowFilter.messagetemplatecontent.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.messagetemplatecontent.inserted_at": string;
  /** Format: timestamp with time zone */
  "rowFilter.messagetemplatecontent.updated_at": string;
  /** Format: character varying */
  "rowFilter.messagetemplatecontent.istype": string;
  /** Format: character varying */
  "rowFilter.messagetemplatecontent.istext": string;
  /** @description talks */
  "body.talks": definitions["talks"];
  /** Format: uuid */
  "rowFilter.talks.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.talks.inserted_at": string;
  /** Format: timestamp with time zone */
  "rowFilter.talks.updated_at": string;
  /** Format: character varying */
  "rowFilter.talks.istype": string;
  /** Format: character varying */
  "rowFilter.talks.messagetype": string;
  /** Format: character varying */
  "rowFilter.talks.messageid": string;
  /** Format: character varying */
  "rowFilter.talks.messagetext": string;
  /** Format: character varying */
  "rowFilter.talks.webhookeventid": string;
  /** Format: boolean */
  "rowFilter.talks.isredelivery": string;
  /** Format: character varying */
  "rowFilter.talks.istimestamp": string;
  /** Format: character varying */
  "rowFilter.talks.replytoken": string;
  /** Format: character varying */
  "rowFilter.talks.ismode": string;
  /**
   * Format: boolean
   * @description このメッセージに対して、返信したかどうか
   */
  "rowFilter.talks.isReply": string;
  /** Format: character varying */
  "rowFilter.talks.userId": string;
  /** @description reserve */
  "body.reserve": definitions["reserve"];
  /** Format: timestamp with time zone */
  "rowFilter.reserve.created_at": string;
  /** Format: date */
  "rowFilter.reserve.date": string;
  /** Format: integer */
  "rowFilter.reserve.member": string;
  /** Format: text */
  "rowFilter.reserve.status": string;
  /** Format: character varying */
  "rowFilter.reserve.lineid": string;
  /** Format: uuid */
  "rowFilter.reserve.reserveid": string;
  /** @description messagetemplate */
  "body.messagetemplate": definitions["messagetemplate"];
  /** Format: uuid */
  "rowFilter.messagetemplate.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.messagetemplate.inserted_at": string;
  /** Format: timestamp with time zone */
  "rowFilter.messagetemplate.updated_at": string;
  /** Format: ARRAY */
  "rowFilter.messagetemplate.content": string;
  /** Format: character varying */
  "rowFilter.messagetemplate.name": string;
  /** @description urls_tags */
  "body.urls_tags": definitions["urls_tags"];
  /** Format: uuid */
  "rowFilter.urls_tags.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.urls_tags.created_at": string;
  /** Format: uuid */
  "rowFilter.urls_tags.url_id": string;
  /** Format: uuid */
  "rowFilter.urls_tags.tag_id": string;
  /** @description autoreplymessage */
  "body.autoreplymessage": definitions["autoreplymessage"];
  /** Format: uuid */
  "rowFilter.autoreplymessage.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.autoreplymessage.inserted_at": string;
  /** Format: timestamp with time zone */
  "rowFilter.autoreplymessage.updated_at": string;
  /** Format: character varying */
  "rowFilter.autoreplymessage.trigger": string;
  /** Format: ARRAY */
  "rowFilter.autoreplymessage.content": string;
  /** @description countup */
  "body.countup": definitions["countup"];
  /** Format: text */
  "rowFilter.countup.url": string;
  /** Format: integer */
  "rowFilter.countup.count": string;
  /** @description pushmessages */
  "body.pushmessages": definitions["pushmessages"];
  /** Format: uuid */
  "rowFilter.pushmessages.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.pushmessages.inserted_at": string;
  /** Format: timestamp with time zone */
  "rowFilter.pushmessages.updated_at": string;
  /** Format: character varying */
  "rowFilter.pushmessages.message": string;
  /** Format: character varying */
  "rowFilter.pushmessages.touserid": string;
  /** Format: character varying */
  "rowFilter.pushmessages.istype": string;
  /** @description tags */
  "body.tags": definitions["tags"];
  /** Format: uuid */
  "rowFilter.tags.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.tags.inserted_at": string;
  /** Format: timestamp with time zone */
  "rowFilter.tags.updated_at": string;
  /** Format: character varying */
  "rowFilter.tags.name": string;
  /** @description customers */
  "body.customers": definitions["customers"];
  /** Format: character varying */
  "rowFilter.customers.lineid": string;
  /** Format: character varying */
  "rowFilter.customers.phone": string;
  /** Format: character varying */
  "rowFilter.customers.email": string;
  /** Format: character varying */
  "rowFilter.customers.address": string;
  /** Format: timestamp with time zone */
  "rowFilter.customers.inserted_at": string;
  /** Format: timestamp with time zone */
  "rowFilter.customers.updated_at": string;
  /** Format: character varying */
  "rowFilter.customers.username": string;
  /** Format: character varying */
  "rowFilter.customers.displayname": string;
  /** Format: text */
  "rowFilter.customers.pictureurl": string;
  /** Format: character varying */
  "rowFilter.customers.status": string;
  /** @description urls */
  "body.urls": definitions["urls"];
  /** Format: uuid */
  "rowFilter.urls.id": string;
  /** Format: character varying */
  "rowFilter.urls.name": string;
  /** Format: timestamp with time zone */
  "rowFilter.urls.createdAt": string;
  /** Format: timestamp with time zone */
  "rowFilter.urls.updatedAt": string;
  /** Format: integer */
  "rowFilter.urls.click": string;
  /** Format: integer */
  "rowFilter.urls.impression": string;
  /** @description customers_tags */
  "body.customers_tags": definitions["customers_tags"];
  /** Format: uuid */
  "rowFilter.customers_tags.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.customers_tags.created_at": string;
  /** Format: uuid */
  "rowFilter.customers_tags.tag_id": string;
  /** Format: character varying */
  "rowFilter.customers_tags.customer_id": string;
}

export interface operations {}

export interface external {}
